In [168]:
import pandas as pd

In [169]:
E_commerce = pd.read_csv('E-Commerce_Shipping_Data.csv', sep=';')

E_commerce.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1

In [170]:
E_commerce

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10994,10995,A,Ship,4,1,252,5,medium,F,1,1538,1
10995,10996,B,Ship,4,1,232,5,medium,F,6,1247,0
10996,10997,C,Ship,5,4,242,5,low,F,4,1155,0
10997,10998,F,Ship,5,2,223,6,medium,M,2,1210,0
10998,10999,D,Ship,2,5,155,5,low,F,6,1639,0

In [171]:
tar = E_commerce['Product_importance']

In [172]:
target = [i for i in tar]

In [173]:
for i in range(len(target)):
    if target[i] == 'low':
        target[i] = 1
        
    if target[i] == 'medium':
        target[i] = 2
        
    if target[i] == 'high':
        target[i] = 3

target

[1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 3,
 1,
 1,
 2,
 2,
 3,
 2,
 2,
 2,
 1,
 3,
 2,
 1,
 3,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 3,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 2,
 3,
 3,
 1,
 2,
 2,
 2,
 3,
 1,
 2,
 1,
 2,
 2,
 3,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 3,
 3,
 2,
 2,
 1,
 2,
 1,
 2,
 3,
 1,
 2,
 2,
 3,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 3,
 3,
 2,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 3,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 3,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 3,
 1,
 1,
 2,
 2,
 3,
 1,
 1,
 1,
 2,
 3,
 2,
 2,
 2,
 2,
 1,
 3,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 3,
 1,
 1,
 1,
 2,
 3,
 2,
 2,
 2,
 2,
 1,
 3,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 3,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 3,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 3,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 3,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 3,
 1,
 2,
 3,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 3,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 3,
 1,
 2,
 2,
 1,
 3,
 3,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 3,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 3,
 3,
 1,
 1,
 2,
 1,
 2,
 3,
 2,
 3,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 3,
 2,
 2,
 2,
 2,
 3,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 3,
 3,
 2,
 2,
 2,
 1,
 2,
 3,
 2,
 3,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 3,
 1,
 3,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 3,
 2,
 3,
 2,
 1,
 2,
 2,
 2,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 1,
 2,
 2,
 2,
 3,
 2,
 1,
 2,
 1,
 1,
 2,
 3,
 2,
 2,
 2,
 3,
 3,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 3,
 2,
 2,
 1,
 1,
 1,
 3,
 2,
 1,
 1,
 1,
 2,
 3,
 2,
 2,
 2,
 3,
 3,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 3,
 2,
 2,
 1,
 1,
 1,
 3,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 3,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 3,
 3,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 3,
 1,
 2,
 1,
 2,
 1,
 3,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 3,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 3,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 3,
 3,
 1,
 1,
 1,
 1,
 2,
 3,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 3,
 3,
 3,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 3,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 3,
 2,
 1,
 2,
 3,
 1,
 3,
 3,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 3,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 3,
 2,
 1,
 2,
 3,
 1,
 3,
 3,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 ...]

In [174]:
E_commerce

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10994,10995,A,Ship,4,1,252,5,medium,F,1,1538,1
10995,10996,B,Ship,4,1,232,5,medium,F,6,1247,0
10996,10997,C,Ship,5,4,242,5,low,F,4,1155,0
10997,10998,F,Ship,5,2,223,6,medium,M,2,1210,0
10998,10999,D,Ship,2,5,155,5,low,F,6,1639,0

In [175]:
coluna = ['ID', 'Warehouse_block', 'Mode_of_Shipment','Product_importance','Gender','Reached.on.Time_Y.N']

In [176]:
E_commerce = E_commerce.drop(columns = coluna)

In [179]:
dados = E_commerce.values

In [181]:
carregar = [dados, target]

[1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 3,
 1,
 1,
 2,
 2,
 3,
 2,
 2,
 2,
 1,
 3,
 2,
 1,
 3,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 3,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 2,
 3,
 3,
 1,
 2,
 2,
 2,
 3,
 1,
 2,
 1,
 2,
 2,
 3,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 3,
 3,
 2,
 2,
 1,
 2,
 1,
 2,
 3,
 1,
 2,
 2,
 3,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 3,
 3,
 2,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 3,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 3,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 3,
 1,
 1,
 2,
 2,
 3,
 1,
 1,
 1,
 2,
 3,
 2,
 2,
 2,
 2,
 1,
 3,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 3,
 1,
 1,
 1,
 2,
 3,
 2,
 2,
 2,
 2,
 1,
 3,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 3,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 3,
 2,
 3,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 3,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 3,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 3,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 3,
 1,
 2,
 3,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 3,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 3,
 1,
 2,
 2,
 1,
 3,
 3,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 3,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 3,
 3,
 1,
 1,
 2,
 1,
 2,
 3,
 2,
 3,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 3,
 2,
 2,
 2,
 2,
 3,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 3,
 3,
 2,
 2,
 2,
 1,
 2,
 3,
 2,
 3,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 3,
 1,
 3,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 3,
 2,
 3,
 2,
 1,
 2,
 2,
 2,
 3,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 1,
 2,
 2,
 2,
 3,
 2,
 1,
 2,
 1,
 1,
 2,
 3,
 2,
 2,
 2,
 3,
 3,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 3,
 2,
 2,
 1,
 1,
 1,
 3,
 2,
 1,
 1,
 1,
 2,
 3,
 2,
 2,
 2,
 3,
 3,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 3,
 2,
 2,
 1,
 1,
 1,
 3,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 3,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 3,
 3,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 3,
 1,
 2,
 1,
 2,
 1,
 3,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 3,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 3,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 3,
 3,
 1,
 1,
 1,
 1,
 2,
 3,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 3,
 3,
 3,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 3,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 3,
 2,
 1,
 2,
 3,
 1,
 3,
 3,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 3,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 3,
 2,
 1,
 2,
 3,
 1,
 3,
 3,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 ...]